using System;
using System.Linq;
using System.Collections.Generic;
using UnityEngine;

namespace GUIDesigner
{
	/// <summary>
	/// Contains general properties for the GUI Designer package.
	/// </summary>
	public class GUIDesignerProperties
	{
		/// <summary>
		/// Set this path to the GUI Designer directory.
		/// </summary>
		public static readonly String GUIDesignerDirectory = String.Format("{0}/GUI Designer", Application.dataPath);

		/// <summary>
		/// The path of the autogenerated menu files.
		/// </summary>
		public static readonly String MenusFolder = String.Format("{0}/Scripts/GUIMenus", Application.dataPath);

		/// <summary>
		/// The path of the editor files.
		/// DO NOT CHANGE THIS!
		/// </summary>
		public static readonly String EditorsFolder = String.Format("{0}/Scripts/Editor", GUIDesignerDirectory);
	}
}